spring:
  application:
    name: zuul

server:
  port: ${PORT:8762}
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:kps_zuul_keystore.jks
    key-store-password: sepstore
    key-store-type: JKS
    key-alias: zuul
#    trust-store: classpath:kp_sep_zuul_truststore.jks
#    trust-store-password: sepstore 
#    trust-store-type: JKS
#    client-auth: want

security:
  require-ssl: true

eureka:
  instance: 
    # Docker
    # hostname: host.docker.internal
    # Normal
    hostname: localhost
    # false: Load balancer does not have available server for client
    prefer-ip-address: true
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
  client:
#    register-with-eureka: true
#    fetch-registry: true
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
      # Docker
      # defaultZone: http://host.docker.internal:8761/eureka/
      # Normal
       
zuul:
  routes:
    requestHandler:
#      path: /requestHandler/**
      serviceId: requestHandler
    bitcoinHandler:
#      path: /bitcoinHandler/**
      serviceId: bitcoinHandler
    cardPaymentHandler:
#      path: /cardPaymentHandler/**
      serviceId: cardPaymentHandler
    payPalHandler:
#      path: /payPalHandler/**
      serviceId: payPalHandler
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  ribbon:
#    eureka:
#      enable: true
#    eager-load:
#      enabled: true
#    isSecure: false
#    readTimeout: 60000
#    connectTimeout: 60000
  host:
    socket-timeout-millis: 300000
  sslHostnameValidationEnabled: false
# u teoriji bi trebalo da je obrnuta logika, ali vrv on konstantno gazi podesavanje!!!!!!!!
# true/false # vrednost true -> Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <192.168.1.3> doesn't match any of the subject alternative names: []

ribbon:
  IsSecure: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
# Setting the property ribbon.eureka.enabled = false will explicitly disable the use of Eureka in Ribbon.
# vrednost true -> Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <192.168.1.3> doesn't match any of the subject alternative names: []
#    mozda false -> (ni ne stigne do zuul)Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: cardPaymentHandler

  TrustStore: classpath:kp_zuul_trustore.jks
  TrustStorePassword: sepstore
  IsHostnameValidationRequired: false
  # vrednost true -> Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <192.168.1.3> doesn't match any of the subject alternative names: []
  # ako se Dn sert i naziv servisa ne poklapaju
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 600000
#    gateway:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 600000